Game.bossUI = (function () {
    "use strict";
    var instance = { initialised: false, elapsed: 0, wasInBattle: false, lastRenderedAttack: 0 };
    function fmt(value) { return Game.utils && Game.utils.formatNumber ? Game.utils.formatNumber(value) : Math.floor(value).toLocaleString(); }
    function timeString(ms) { var s=Math.max(0,Math.ceil(ms/1000)),m=Math.floor(s/60); return (m<10?"0":"")+m+":"+((s%60)<10?"0":"")+(s%60); }
    function showTab(selector) { var $trigger=$(selector); if($trigger.length&&$trigger.tab)$trigger.tab('show'); }
    function portrait(id){ return Game.visualAssets&&Game.visualAssets.getMinerPortrait?Game.visualAssets.getMinerPortrait(id):'Assets/miners/portraits/'+id+'.webp'; }
    function rarityKey(entry){ var n=(entry.definition.rarity&&entry.definition.rarity.name||'common').toLowerCase(); return n.replace(/[^a-z]/g,''); }
    instance.initialise=function(){
        if(this.initialised)return;
        if(!$('#bossChamberTopTab').length) $('#tabList').append('<li role="presentation" id="bossChamberTopTab" class="myco-hidden-system-tab" aria-hidden="true"><a href="#bossChamberPage" role="tab" data-toggle="tab" tabindex="-1">Boss Chamber</a></li>');
        if(!$('#bossChamberPage').length) $('#tabContent').append('<div role="tabpanel" class="tab-pane fade myco-boss-chamber-page" id="bossChamberPage"><div id="bossChamberContent"></div></div>');
        if(!$('#planetGateArena').length) $('#tabContent').append('<div id="planetGateArena" class="myco-gate-overlay hidden"><div class="myco-gate-arena"><button id="closeGateArena" class="btn btn-default myco-gate-close">Close</button><div id="gatePrepContent"></div></div></div>');
        $(document).on('click','#closeGateArena',function(){if(!Game.bosses.activeBattle)$('#planetGateArena').addClass('hidden');});
        $(document).on('click','.boss-team-toggle',function(){Game.bosses.toggleTeamMember($(this).attr('data-miner-id'));instance.render();});
        $(document).on('click','#bossAutoTeam',function(){Game.bosses.autoSelectTeam();instance.render();});
        $(document).on('click','#bossStartGate',function(){var id=$(this).attr('data-boss-id');if(Game.bosses.startBattle(id)){instance.wasInBattle=true;instance.openChamber();}instance.render();});
        $(document).on('click','#bossAttack',function(){if(Game.bosses.attackBoss()){instance.playAttack();}instance.render();});
        $(document).on('click','#bossRetreat',function(){Game.bosses.cancelBattle();instance.wasInBattle=false;instance.returnToPlanets();instance.render();});
        this.initialised=true;this.render();
    };
    instance.openArena=function(){$('#planetGateArena').removeClass('hidden');this.render();};
    instance.openChamber=function(){$('#planetGateArena').addClass('hidden');$('body').addClass('myco-in-boss-chamber');this.renderChamber();showTab('#bossChamberTopTab a');var self=this;setTimeout(function(){self.renderChamber();},0);};
    instance.returnToPlanets=function(){$('body').removeClass('myco-in-boss-chamber');$('#planetGateArena').addClass('hidden');showTab('#planetsTopTab a');};
    instance.playAttack=function(){var $page=$('#bossChamberPage');$page.removeClass('myco-attack-pulse');void($page[0]&&$page[0].offsetWidth);$page.addClass('myco-attack-pulse');setTimeout(function(){$page.removeClass('myco-attack-pulse');},520);};
    instance.buildPrep=function(boss){
        var miners=Game.miners.getEntriesSorted(),team=[];
        for(var i=0;i<miners.length;i++){var m=miners[i];if(m.owned<=0)continue;var sel=Game.bosses.selectedTeam.indexOf(m.id)>=0,hp=Game.miners.getCurrentHealth(m.id),max=Game.miners.getMaxHealth(m.id);team.push('<button class="boss-team-toggle myco-team-chip '+(sel?'selected':'')+'" data-miner-id="'+m.id+'" '+(hp<=0?'disabled':'')+'><img src="'+portrait(m.id)+'" alt=""><strong>'+m.definition.name+'</strong><span>HP '+fmt(hp)+' / '+fmt(max)+' • ATK '+fmt(Game.bosses.getMinerAttackPower(m.id))+'</span></button>');}
        var health=Game.bosses.getTeamHealth(),ready=Game.planets.isGateReady(boss.planetId),planet=Game.planets.getPlanet(boss.planetId);
        return '<section class="myco-gate-visual" style="--gate-arena:url(Assets/arenas/'+boss.planetId+'.webp)"><div class="myco-gate-visual-shade"></div><div class="myco-gate-header"><img src="'+boss.image+'" alt="'+boss.name+'"><div><div class="myco-eyebrow">PLANETARY GATE GUARDIAN</div><h2>'+boss.name+'</h2><p>'+boss.description+'</p><div class="myco-gate-world">'+planet.name+' Boss Chamber</div></div></div></section><section class="myco-panel-grid"><article class="myco-panel"><h3>Choose combat squad</h3><div class="myco-boss-health-label"><span>Total team HP</span><strong>'+fmt(health.current)+' / '+fmt(health.max)+'</strong></div><progress class="myco-native-progress team" value="'+health.current+'" max="'+Math.max(1,health.max)+'"></progress><button id="bossAutoTeam" class="btn btn-default">Select Strongest Healthy Team</button><div class="myco-boss-team-grid">'+(team.join('')||'<p>No healthy miners available.</p>')+'</div></article><article class="myco-panel"><h3>Gate Battle</h3><div class="myco-kv-list"><div><span>Boss HP</span><strong>'+fmt(boss.maxHealth)+'</strong></div><div><span>Squad strike</span><strong>'+fmt(Game.bosses.getTeamAttackPower(Game.bosses.selectedTeam))+'</strong></div><div><span>Time limit</span><strong>'+timeString(boss.durationSeconds*1000)+'</strong></div></div><button id="bossStartGate" class="btn btn-warning btn-lg" data-boss-id="'+boss.id+'" '+(!ready||Game.bosses.getTeamPower()<=0?'disabled':'')+'>Begin Gate Battle</button></article></section>';
    };
    instance.buildChamber=function(snap,boss){
        var planet=Game.planets.getPlanet(boss.planetId),teamCards=[];
        for(var i=0;i<snap.team.length;i++){var id=snap.team[i],e=Game.miners.getEntry(id);if(!e)continue;var hp=Game.miners.getCurrentHealth(id),max=Game.miners.getMaxHealth(id);teamCards.push('<article class="myco-combat-miner rarity-'+rarityKey(e)+'"><img src="'+portrait(id)+'" alt="'+e.definition.name+'"><div class="myco-combat-miner-meta"><strong>'+e.definition.name+'</strong><span>Lv. '+Math.max(1,e.level)+' • ATK '+fmt(Game.bosses.getMinerAttackPower(id))+'</span><progress value="'+hp+'" max="'+Math.max(1,max)+'"></progress></div></article>');}
        var result=snap.lastAttackDamage>0?'<div class="myco-floating-damage '+(snap.lastAttackCritical?'critical':'')+'">'+(snap.lastAttackCritical?'CRITICAL!<br>':'')+'-'+fmt(snap.lastAttackDamage)+'</div>':'';
        return '<main class="myco-cinematic-chamber" style="--arena-desktop:url(Assets/arenas/'+boss.planetId+'.webp);--arena-mobile:url(Assets/arenas/'+boss.planetId+'-mobile.webp)"><div class="myco-chamber-vignette"></div><header class="myco-chamber-header"><button id="bossRetreat" class="myco-chamber-retreat">← Retreat</button><div class="myco-boss-title"><span>PLANETARY BOSS</span><h1>'+boss.name+'</h1><small>'+planet.name+'</small></div><div class="myco-chamber-timer"><span>Battle timer</span><strong>'+timeString(snap.remainingMs)+'</strong></div></header><section class="myco-boss-hud"><div class="myco-boss-hp-row"><span>Boss HP</span><strong>'+fmt(snap.health)+' / '+fmt(boss.maxHealth)+'</strong><em>'+Math.ceil(snap.healthPercent)+'%</em></div><div class="myco-boss-hp-track"><i style="width:'+Math.max(0,snap.healthPercent)+'%"></i></div><div class="myco-phase-badges"><span>'+snap.phase.name+'</span><span>Counterattacks disabled</span><span>'+planet.name+' effect</span></div></section><aside class="myco-squad-status"><h3>Squad Status</h3><div><span>Squad HP</span><strong>'+fmt(snap.teamHealth.current)+' / '+fmt(snap.teamHealth.max)+'</strong></div><progress value="'+snap.teamHealth.current+'" max="'+Math.max(1,snap.teamHealth.max)+'"></progress><div><span>Total Attack</span><strong>⚔ '+fmt(snap.teamAttack)+'</strong></div><div><span>Attacks</span><strong>'+snap.attacks+'</strong></div><div><span>Total Damage</span><strong>'+fmt(snap.totalDamage)+'</strong></div></aside><section class="myco-boss-stage"><img class="myco-stage-boss" src="'+boss.image+'" alt="'+boss.name+'">'+result+'<div class="myco-stage-floor"></div></section><section class="myco-combat-squad">'+teamCards.join('')+'</section><section class="myco-chamber-actions"><button id="bossAttack" class="myco-attack-boss" '+(snap.attackReadyInMs>0?'disabled':'')+'>⚔ ATTACK BOSS <small>'+(snap.attackReadyInMs>0?'Ready in '+(Math.ceil(snap.attackReadyInMs/100)/10)+'s':'All miners strike together')+'</small></button><div class="myco-last-strike">'+(snap.lastAttackDamage>0?(snap.lastAttackCritical?'Critical strike':'Last strike')+': '+fmt(snap.lastAttackDamage):'Strike the guardian before time expires.')+'</div></section></main>';
    };
    instance.renderChamber=function(){if(!this.initialised)return;var snap=Game.bosses.getActiveSnapshot(),boss=snap?snap.boss:null;if(!snap||!boss){$('#bossChamberContent').html('<section class="myco-panel myco-empty-chamber"><h3>No active Gate Battle</h3><p>Return to Planets and begin a battle.</p></section>');return;}$('#bossChamberContent').html(this.buildChamber(snap,boss));};
    instance.render=function(){if(!this.initialised)return;var snap=Game.bosses.getActiveSnapshot(),prepBoss=Game.bosses.getBossForPlanet(Game.planets.activePlanetId);if(prepBoss)$('#gatePrepContent').html(this.buildPrep(prepBoss));else $('#gatePrepContent').html('<p>No guardian assigned.</p>');if(snap)this.renderChamber();else if($('#bossChamberPage').hasClass('active'))this.renderChamber();};
    instance.update=function(d){this.elapsed+=d;if(this.elapsed>=0.25){this.elapsed=0;var active=!!Game.bosses.activeBattle;this.render();if(active){this.wasInBattle=true;if(!$('#bossChamberPage').hasClass('active'))this.openChamber();}else if(this.wasInBattle){this.wasInBattle=false;this.returnToPlanets();}}};
    return instance;
}());
